### ISSUE TITLE
Remove OpenLayers 2 references in figismapdata

### ISSUE THREAD

**Issue by eblondel** [openfigis/FigisMap#16]
The javascript resoure `figismapdata` currently exposes evaluable javascript code referencing OpenLayers 2 classes. For the upgrade to OL3, it has to be changed as follows:
- coordinate: `"new OpenLayers.LonLat(x, y)"` (as `string`) to be replaced by `[x,y]` (as `array`)
- extent: `"new OpenLayers.Bounds(xmin, ymin, xmax, ymax)"` (as `string`) to be replaced by `[xmin, ymin, xmax, ymax]` (as `array`)

**Comment by marcobalestra** [comment]
We should be careful with this, being such coordinates directly inserted by Fabio Carocci in the related XML.
I see two options:
1) Have a different FigisMap XML data source, ready for OL3
2) Have a different moniker transforming OL2 data into OL3 data.
First option (more efficient) could be hard to be maintained during the transition, while second option could support both OL2 and OL3.
I suppose that option 2. could be safer.

**Comment by eblondel** [comment]
i remember we worked on this in the past, AFAIK, we have a moniker that adds the OpenLayers 2 classes. Can you clarify if we have 2 different levels of data: ie (1) an XML data edited by Fabio, which does not containing OL 2 javascript code, (2) a moniker that takes this source and wraps coordinates and bounds with OL2 classes.
If it's the case, we may work only on (2), and providing a new moniker not wrapping data with OL2 classes.
If not, ie data exposed through moniker (with OL2 classes) and the source are the same, then option 2 is better indeed, otherwise 

Let me know

**Comment by marcobalestra** [comment]
OL2 classes are added in the XML, not by the moniker.
By the way I created a new moniker translating content: http://figisapps.fao.org/figis/moniker.json/figismapdata3

Please note that content is still a string, but it is evaluated at runtime.

**Comment by eblondel** [comment]
Just tested the new moniker, works well!
