### ISSUE TITLE
FAO logo/watermark distortioned in some factsheet maps

### ISSUE THREAD

**Issue by eblondel** [openfigis/FigisMap#27]
See http://figisapps.fao.org/fishery/rfb/swiofc/en

**Comment by marcobalestra** [comment]
FIGIS:**fi/figis/organization/format/FigisMapOrg.xsl** updated.
Needs to be deployed in prod at release time!

**Comment by eblondel** [comment]
Does it make sense to have this file in this git repository?

**Comment by marcobalestra** [comment]
It's a completely different path, and server...

**Comment by eblondel** [comment]
ok, no problem, as long as we are aware of these files.
